create table address (id bigint generated by default as identity, country varchar(255), number integer, postal_code integer, street varchar(255), fk_company bigint, primary key (id));
create table company (id bigint generated by default as identity, tva varchar(255) not null, fk_main_address bigint not null, primary key (id));
create table contact (id bigint generated by default as identity, firstname varchar(255) not null, lastname varchar(255) not null, status varchar(255) not null, tva varchar(255), fk_address bigint not null, fk_company bigint, primary key (id));
alter table address add constraint fk_address_to_company foreign key (fk_company) references company;
alter table company add constraint FK_company_to_address foreign key (fk_main_address) references address;
alter table contact add constraint FK_contact_to_address foreign key (fk_address) references address;
alter table contact add constraint fk_contact_to_company foreign key (fk_company) references company;
